[project]
name = "test-robot-environments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gymnasium>=1.1.1",
    "mujoco>=3.3.3",
    "numpy>=2.3.0",
]
